### ISSUE TITLE
Current build is broken

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#92]
I am not sure, but I think this might be related to:

https://www.drupal.org/node/2008186

Is this something easy to fix up?

**Comment by mglaman** [comment]
The issue is the commerce product bundles. I'm not sure if defaultconfig is building before the bundles are processed, or cache race condition. I tried fixing this onmy own quick by putting defaultconfig last on dependencies list (fixed the Panopoly child distributions lettered A,B,C,D,E issue) but that didn't work.

The option is to apply a patch which lets defaultconfig gracefully fail on install..but that's a bandaid

**Comment by lsolesen** [comment]
Related to https://github.com/vih/vih-build/issues/81. I really wanted to use defaultconfig, but it seems to cause a lot of grief :(

**Comment by mglaman** [comment]
Well I think you can safely use Features for permissions. You don't plan on overriding the default permissions once in production, which is the intended usage of defaultconfig.

**Comment by lsolesen** [comment]
Yeah. However, that was the original idea ehen i spend hours implementing
defaultconfig :)
Den 27/09/2015 15.15 skrev "Matt Glaman" notifications@github.com:

**Comment by mglaman** [comment]
:( Well. Perhaps I can take a poke. I'll look @ dsnopek's suggestion in the Drupal.org node

**Comment by mglaman** [comment]
Just found https://www.drupal.org/node/2334409. It seems like this issue does related to 2.5 to 2.6 changes (I don't recall build being broken until recently.)

**Comment by mglaman** [comment]
See
- https://www.drupal.org/node/2576815
- https://www.drupal.org/node/2576819

**Comment by lsolesen** [comment]
So you actually got this fixed :)

**Comment by mglaman** [comment]
Yep! I can't believe I missed it before. Had it happen to myself. It's a flaw with when the defaultconfig module ran.
